# Generated by Django 5.1.5 on 2025-01-27 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('acao', models.CharField(blank=True, choices=[('Louvor', 'Louvor'), ('Mensagem', 'Mensagem'), ('Sermao', 'Sermao')], max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='programacao.diaprogramacao')),
            ],
        ),
    ]
