# Generated by Django 5.1.5 on 2025-01-28 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemprogramacao',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordemprogramacao',
            name='programacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ordens', serialize=False, to='programacao.diaprogramacao'),
        ),
    ]
