# Generated by Django 5.1.5 on 2025-01-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0002_remove_ordemprogramacao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemprogramacao',
            name='tarefa_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordemprogramacao',
            name='programacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='programacao.diaprogramacao'),
        ),
    ]
