# Generated by Django 5.1.5 on 2025-01-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacao', '0003_ordemprogramacao_tarefa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemprogramacao',
            name='tarefa_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
